### ISSUE TITLE
drop all `stage-x`, require special plugins

### ISSUE THREAD

**Issue by ghost** [newraina/babel-preset-esnext#1]
such as

```
transform-function-bind
transform-async-to-generator
transform-class-properties
transform-object-rest-spread
syntax-trailing-function-commas
transform-exponentiation-operator
transform-export-extensions
```

We should use `babel-preset-es20xx` only (someday 🙏 ) !

**Comment by ghost** [comment]
upupup!!! @newraina

**Comment by newraina** [comment]
done: https://github.com/newraina/babel-preset-esnext/commit/95c9b389af148ebdf12570c7d45b29a0836722dc

**Comment by newraina** [comment]
这个看起来比不停调整 plugin 更灵活：https://github.com/babel/babel-preset-env

**Comment by ghost** [comment]
没必要抠的这么细！

发自我的 iPhone
